### ISSUE TITLE
New Feature: automatic merge / un-merge

### ISSUE THREAD

**Issue by jeromevalentin** [jeanpaulattard/json-to-properties#2]
Would it be possible to add an option (like -m=bundle.properties) to merge automatically all the json files into one single properties file?

You should add a first level key which corresponds to the original json filename.
And use that first key to unmerge them when used with the option '-r -m=bundle.properties'

This would be useful to use all the Java ResourceBundle translation tools, to translate web applications ;-)

**Comment by jeanpaulattard** [comment]
Hi Jerome!

Thank you for the feedback! Will be looking into implementing what you've requested. :)

Watch the space!

**Comment by jeanpaulattard** [comment]
Released with v1.1.0
